version: "3.5"

services:
  orion:
    image: fiware/orion:3.10.1
    hostname: orion
    container_name: fiware-orion
    depends_on:
      - mongo-db
    expose:
      - "1026"
    ports:
      - "1026:1026"
    command: -dbhost mongo-db -logLevel DEBUG
    healthcheck:
      test: curl --fail -s http://orion:1026/version || exit 1

  mongo-db:
    image: mongo:3.6
    hostname: mongo-db
    container_name: db-mongo
    expose:
      - "27017"
    ports:
      - "27017:27017"
    command: --nojournal
    volumes:
      - mongo-db:/data/db

  mongo-users:
    image: mongo:6
    container_name: mongo-users
    ports:
      - "27018:27017"
    volumes:
      - mongo-users-data:/data/db

  backend:
    build: ../backend
    container_name: backend-server
    ports:
      - "5000:5000"
    depends_on:
      - mongo-users
    environment:
      - MONGO_URI=mongodb://mongo-users:27017/ContextBrokerUsers
      - JWT_SECRET=jwt_secret
    volumes:
      - ../backend:/usr/src/app
    working_dir: /usr/src/app
    command: node server.js

volumes:
  mongo-db: {}
  mongo-users-data: {}
